'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace ECSSSOAP
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ECSSWSDLBinding", [Namespace]:="http://phpserver1.prexeco.com/ECSSWSDL/server_wsdl.php")>  _
    Partial Public Class ECSSWSDL
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private helloOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetQuerySQL_SV5_WSDLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetQueryColumnTitle_SV5_WSDLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ExecuateQuerySQL_SV5_WSDLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ExecuateQuerySQLCluster_SV5_WSDLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateUserUsage_wsdlOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ECSS.My.MySettings.Default.ECSS_ECSSSOAP_ECSSWSDL
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event helloCompleted As helloCompletedEventHandler
        
        '''<remarks/>
        Public Event GetQuerySQL_SV5_WSDLCompleted As GetQuerySQL_SV5_WSDLCompletedEventHandler
        
        '''<remarks/>
        Public Event GetQueryColumnTitle_SV5_WSDLCompleted As GetQueryColumnTitle_SV5_WSDLCompletedEventHandler
        
        '''<remarks/>
        Public Event ExecuateQuerySQL_SV5_WSDLCompleted As ExecuateQuerySQL_SV5_WSDLCompletedEventHandler
        
        '''<remarks/>
        Public Event ExecuateQuerySQLCluster_SV5_WSDLCompleted As ExecuateQuerySQLCluster_SV5_WSDLCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateUserUsage_wsdlCompleted As UpdateUserUsage_wsdlCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ECSSWSDL#hello", RequestNamespace:="urn:ECSSWSDL", ResponseNamespace:="urn:ECSSWSDL")>  _
        Public Function hello(ByVal name As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("hello", New Object() {name})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub helloAsync(ByVal name As String)
            Me.helloAsync(name, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub helloAsync(ByVal name As String, ByVal userState As Object)
            If (Me.helloOperationCompleted Is Nothing) Then
                Me.helloOperationCompleted = AddressOf Me.OnhelloOperationCompleted
            End If
            Me.InvokeAsync("hello", New Object() {name}, Me.helloOperationCompleted, userState)
        End Sub
        
        Private Sub OnhelloOperationCompleted(ByVal arg As Object)
            If (Not (Me.helloCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent helloCompleted(Me, New helloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://testdomain/ECSSWSDL/server_wsdl.php/GetQuerySQL_SV5_WSDL", RequestNamespace:="", ResponseNamespace:="")>  _
        Public Function GetQuerySQL_SV5_WSDL(ByVal uid As String, ByVal pwd As String, ByVal sql As String) As <System.Xml.Serialization.SoapElementAttribute("return")> Object()
            Dim results() As Object = Me.Invoke("GetQuerySQL_SV5_WSDL", New Object() {uid, pwd, sql})
            Return CType(results(0),Object())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetQuerySQL_SV5_WSDLAsync(ByVal uid As String, ByVal pwd As String, ByVal sql As String)
            Me.GetQuerySQL_SV5_WSDLAsync(uid, pwd, sql, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetQuerySQL_SV5_WSDLAsync(ByVal uid As String, ByVal pwd As String, ByVal sql As String, ByVal userState As Object)
            If (Me.GetQuerySQL_SV5_WSDLOperationCompleted Is Nothing) Then
                Me.GetQuerySQL_SV5_WSDLOperationCompleted = AddressOf Me.OnGetQuerySQL_SV5_WSDLOperationCompleted
            End If
            Me.InvokeAsync("GetQuerySQL_SV5_WSDL", New Object() {uid, pwd, sql}, Me.GetQuerySQL_SV5_WSDLOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetQuerySQL_SV5_WSDLOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetQuerySQL_SV5_WSDLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetQuerySQL_SV5_WSDLCompleted(Me, New GetQuerySQL_SV5_WSDLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://testdomain/ECSSWSDL/server_wsdl.php/GetQueryColumnTitle_SV5_WSDL", RequestNamespace:="", ResponseNamespace:="")>  _
        Public Function GetQueryColumnTitle_SV5_WSDL(ByVal uid As String, ByVal pwd As String, ByVal sql As String) As <System.Xml.Serialization.SoapElementAttribute("return")> Object()
            Dim results() As Object = Me.Invoke("GetQueryColumnTitle_SV5_WSDL", New Object() {uid, pwd, sql})
            Return CType(results(0),Object())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetQueryColumnTitle_SV5_WSDLAsync(ByVal uid As String, ByVal pwd As String, ByVal sql As String)
            Me.GetQueryColumnTitle_SV5_WSDLAsync(uid, pwd, sql, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetQueryColumnTitle_SV5_WSDLAsync(ByVal uid As String, ByVal pwd As String, ByVal sql As String, ByVal userState As Object)
            If (Me.GetQueryColumnTitle_SV5_WSDLOperationCompleted Is Nothing) Then
                Me.GetQueryColumnTitle_SV5_WSDLOperationCompleted = AddressOf Me.OnGetQueryColumnTitle_SV5_WSDLOperationCompleted
            End If
            Me.InvokeAsync("GetQueryColumnTitle_SV5_WSDL", New Object() {uid, pwd, sql}, Me.GetQueryColumnTitle_SV5_WSDLOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetQueryColumnTitle_SV5_WSDLOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetQueryColumnTitle_SV5_WSDLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetQueryColumnTitle_SV5_WSDLCompleted(Me, New GetQueryColumnTitle_SV5_WSDLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://testdomain/ECSSWSDL/server_wsdl.php/ExecuateQuerySQL_SV5_WSDL", RequestNamespace:="", ResponseNamespace:="")>  _
        Public Function ExecuateQuerySQL_SV5_WSDL(ByVal uid As String, ByVal pwd As String, ByVal sql As String) As <System.Xml.Serialization.SoapElementAttribute("return")> Boolean
            Dim results() As Object = Me.Invoke("ExecuateQuerySQL_SV5_WSDL", New Object() {uid, pwd, sql})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ExecuateQuerySQL_SV5_WSDLAsync(ByVal uid As String, ByVal pwd As String, ByVal sql As String)
            Me.ExecuateQuerySQL_SV5_WSDLAsync(uid, pwd, sql, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ExecuateQuerySQL_SV5_WSDLAsync(ByVal uid As String, ByVal pwd As String, ByVal sql As String, ByVal userState As Object)
            If (Me.ExecuateQuerySQL_SV5_WSDLOperationCompleted Is Nothing) Then
                Me.ExecuateQuerySQL_SV5_WSDLOperationCompleted = AddressOf Me.OnExecuateQuerySQL_SV5_WSDLOperationCompleted
            End If
            Me.InvokeAsync("ExecuateQuerySQL_SV5_WSDL", New Object() {uid, pwd, sql}, Me.ExecuateQuerySQL_SV5_WSDLOperationCompleted, userState)
        End Sub
        
        Private Sub OnExecuateQuerySQL_SV5_WSDLOperationCompleted(ByVal arg As Object)
            If (Not (Me.ExecuateQuerySQL_SV5_WSDLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ExecuateQuerySQL_SV5_WSDLCompleted(Me, New ExecuateQuerySQL_SV5_WSDLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://testdomain/ECSSWSDL/server_wsdl.php/ExecuateQuerySQLCluster_SV5_WSDL", RequestNamespace:="", ResponseNamespace:="")>  _
        Public Function ExecuateQuerySQLCluster_SV5_WSDL(ByVal uid As String, ByVal pwd As String, ByVal sql As String, ByVal delimiter As String) As <System.Xml.Serialization.SoapElementAttribute("return")> Object()
            Dim results() As Object = Me.Invoke("ExecuateQuerySQLCluster_SV5_WSDL", New Object() {uid, pwd, sql, delimiter})
            Return CType(results(0),Object())
        End Function
        
        '''<remarks/>
        Public Overloads Sub ExecuateQuerySQLCluster_SV5_WSDLAsync(ByVal uid As String, ByVal pwd As String, ByVal sql As String, ByVal delimiter As String)
            Me.ExecuateQuerySQLCluster_SV5_WSDLAsync(uid, pwd, sql, delimiter, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ExecuateQuerySQLCluster_SV5_WSDLAsync(ByVal uid As String, ByVal pwd As String, ByVal sql As String, ByVal delimiter As String, ByVal userState As Object)
            If (Me.ExecuateQuerySQLCluster_SV5_WSDLOperationCompleted Is Nothing) Then
                Me.ExecuateQuerySQLCluster_SV5_WSDLOperationCompleted = AddressOf Me.OnExecuateQuerySQLCluster_SV5_WSDLOperationCompleted
            End If
            Me.InvokeAsync("ExecuateQuerySQLCluster_SV5_WSDL", New Object() {uid, pwd, sql, delimiter}, Me.ExecuateQuerySQLCluster_SV5_WSDLOperationCompleted, userState)
        End Sub
        
        Private Sub OnExecuateQuerySQLCluster_SV5_WSDLOperationCompleted(ByVal arg As Object)
            If (Not (Me.ExecuateQuerySQLCluster_SV5_WSDLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ExecuateQuerySQLCluster_SV5_WSDLCompleted(Me, New ExecuateQuerySQLCluster_SV5_WSDLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://phpserver1.prexeco.com/ECSSWSDL/server_wsdl.php/UpdateUserUsage_wsdl", RequestNamespace:="http://phpserver1.prexeco.com/ECSSWSDL/server_wsdl.php", ResponseNamespace:="http://phpserver1.prexeco.com/ECSSWSDL/server_wsdl.php")>  _
        Public Function UpdateUserUsage_wsdl(ByVal strUsage As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("UpdateUserUsage_wsdl", New Object() {strUsage})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UpdateUserUsage_wsdlAsync(ByVal strUsage As String)
            Me.UpdateUserUsage_wsdlAsync(strUsage, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateUserUsage_wsdlAsync(ByVal strUsage As String, ByVal userState As Object)
            If (Me.UpdateUserUsage_wsdlOperationCompleted Is Nothing) Then
                Me.UpdateUserUsage_wsdlOperationCompleted = AddressOf Me.OnUpdateUserUsage_wsdlOperationCompleted
            End If
            Me.InvokeAsync("UpdateUserUsage_wsdl", New Object() {strUsage}, Me.UpdateUserUsage_wsdlOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateUserUsage_wsdlOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateUserUsage_wsdlCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateUserUsage_wsdlCompleted(Me, New UpdateUserUsage_wsdlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub helloCompletedEventHandler(ByVal sender As Object, ByVal e As helloCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class helloCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub GetQuerySQL_SV5_WSDLCompletedEventHandler(ByVal sender As Object, ByVal e As GetQuerySQL_SV5_WSDLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetQuerySQL_SV5_WSDLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub GetQueryColumnTitle_SV5_WSDLCompletedEventHandler(ByVal sender As Object, ByVal e As GetQueryColumnTitle_SV5_WSDLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetQueryColumnTitle_SV5_WSDLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub ExecuateQuerySQL_SV5_WSDLCompletedEventHandler(ByVal sender As Object, ByVal e As ExecuateQuerySQL_SV5_WSDLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ExecuateQuerySQL_SV5_WSDLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub ExecuateQuerySQLCluster_SV5_WSDLCompletedEventHandler(ByVal sender As Object, ByVal e As ExecuateQuerySQLCluster_SV5_WSDLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ExecuateQuerySQLCluster_SV5_WSDLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub UpdateUserUsage_wsdlCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateUserUsage_wsdlCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateUserUsage_wsdlCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
